language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.7.*"

matrix:
  include:
    - php: 5.3.3
      env: USE_DEPS="lowest"
    - php: 5.6
      env: SYMFONY_VERSION="2.1.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.2.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.4.*" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 5.6
      env: SYMFONY_VERSION="2.5.*" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.*" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*" SYMFONY_DEPRECATIONS_HELPER="weak"
  fast_finish: true

install:
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
  - bash travis_install_dependencies.sh

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;

notifications:
  email:
    on_success: always
    on_failure: always

# use container-based infrastructure
sudo: false

# cache Composer's package cache
cache:
  directories:
    - $HOME/.composer/cache
